### ISSUE TITLE
Trouble with saving nodes created with capture templates.

### ISSUE THREAD

**Issue by andersjohansson** [ThomasFKJorna/org-roam-timestamps#10]
Using the default org-roam-capture-templates and calling `org-roam-node-find`, an org capture buffer is opened, but is not yet saved to a file. On saving (`save-buffer`) or finishing the capture (`C-c C-c`), `org-roam-timestamps--on-save` is called but encounters problems.

I get "( wrong-type-argument number-or-marker-p nil)" as for #7, and this is in `org-roam-timestamps--add-ctime`.

The buffer registers as an org-roam buffer, but the `org-roam-node-at-point` returns a fairly empty struct with only `:id` and `:point` set. When `org-roam-timestamps--add-ctime`, we don’t have a level so the check `(= 0 level)` errors out.

Is this a problem with `org-roam` (should we have more info for the current node already?) or `org-roam-timestamps` assuming that this information should be available when it is not?

**Comment by ThomasFKJorna** [comment]
I've been having this issue as well, it's probably something to do with org-roam-timestamps. I don't have a lot of time to debug this at the moment, but I will fix it eventually!

**Comment by ThomasFKJorna** [comment]
Actually that was a super simple fix, thanks for pointing out the problem!

**Comment by ThomasFKJorna** [comment]
I will close this for now, feel free to open it back up if it's still broken!
