### ISSUE TITLE
( wrong-type-argument number-or-marker-p nil) on saving org-roam node

### ISSUE THREAD

**Issue by prashantnag93** [ThomasFKJorna/org-roam-timestamps#7]
I am getting the following error : `Error (before-save-hook): Error running hook "org-roam-timestamps--on-save" because: (wrong-type-argument number-or-marker-p nil)`

**Comment by ThomasFKJorna** [comment]
I think this should be fixed along with #10 !

**Comment by ThomasFKJorna** [comment]
Feel free to open it back up if it is still broken.
